import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const { regroupReference } = require('../scripts/apidocs/sidebar.cjs');

const doc = (id) => ({ type: 'doc', id });
const category = (label, items) => ({ type: 'category', label, items });

const contexts = [
  { id: 'platform', title: 'Platform', slug: 'platform', collapsed: true },
  { id: 'design', title: 'Design', slug: 'design', collapsed: true },
  { id: 'common', title: 'Common', slug: 'common', collapsed: true },
];

const generated = [
  category('common', [
    category('Operations', [category('Directives', [doc('reference/common/operations/directives/skip')])]),
    category('Types', [category('Directives', [doc('reference/common/types/directives/deprecated')])]),
    doc('reference/common/overview'),
  ]),
  category('design', [
    category('Operations', [category('Queries', [doc('reference/design/operations/queries/des-project-by-id')])]),
    category('Types', [category('Objects', [doc('reference/design/types/objects/des-project')])]),
    doc('reference/design/overview'),
  ]),
  category('platform', [
    category('Operations', [category('Queries', [doc('reference/platform/operations/queries/node')])]),
  ]),
];

test('orders BCs as in the manifest, relabels them and links overviews', () => {
  const out = regroupReference(generated, { contexts, experimentalDocIds: new Set() });
  assert.deepEqual(out.map((c) => c.label), ['Platform', 'Design', 'Common']);
  assert.deepEqual(out[1].link, { type: 'doc', id: 'reference/design/overview' });
  assert.equal(out[0].link, undefined);
  assert.equal(out[1].collapsed, true);
});

test('flattens Operations/Types unless labels would collide', () => {
  const out = regroupReference(generated, { contexts, experimentalDocIds: new Set() });
  assert.deepEqual(out[1].items.map((i) => i.label), ['Queries', 'Objects']);
  assert.deepEqual(out[2].items.map((i) => i.label), ['Operations', 'Types']);
});

test('marks experimental docs', () => {
  const out = regroupReference(generated, {
    contexts,
    experimentalDocIds: new Set(['reference/design/operations/queries/des-project-by-id']),
  });
  assert.equal(out[1].items[0].items[0].className, 'sidebar-exp');
  assert.equal(out[1].items[1].items[0].className, undefined);
});

test('orders the Deprecated group last, collapsed, with BC sub-categories relabelled and flattened', () => {
  const withDeprecated = [
    category('deprecated', [
      category('design', [
        category('Operations', [category('Queries', [doc('reference/deprecated/design/operations/queries/des-old')])]),
        category('Types', [category('Objects', [doc('reference/deprecated/design/types/objects/des-legacy')])]),
      ]),
      category('platform', [
        category('Operations', [category('Queries', [doc('reference/deprecated/platform/operations/queries/old-node')])]),
      ]),
    ]),
    ...generated,
  ];
  const out = regroupReference(withDeprecated, { contexts, experimentalDocIds: new Set() });
  assert.deepEqual(out.map((c) => c.label), ['Platform', 'Design', 'Common', 'Deprecated']);
  const deprecated = out.at(-1);
  assert.equal(deprecated.collapsed, true);
  assert.equal(deprecated.collapsible, true);
  assert.deepEqual(deprecated.items.map((c) => c.label), ['Platform', 'Design']);
  assert.deepEqual(deprecated.items[1].items.map((i) => i.label), ['Queries', 'Objects']);
  assert.equal(deprecated.items[1].collapsed, true);
});

test('sidebarItemsGenerator leaves the guides category to Docusaurus', async () => {
  const { sidebarItemsGenerator } = require('../scripts/apidocs/sidebar.cjs');
  const items = [doc('guides/getting-started'), doc('guides/errors')];
  const out = await sidebarItemsGenerator({
    defaultSidebarItemsGenerator: async () => items,
    item: { type: 'autogenerated', dirName: 'guides' },
  });
  assert.equal(out, items);
});

test('sidebars.js puts Guides before Reference', () => {
  const { docs } = require('../sidebars.js');
  assert.deepEqual(docs.map((item) => (typeof item === 'string' ? item : item.label)), ['index', 'Guides', 'Reference']);
  assert.deepEqual(docs[1].items, [{ type: 'autogenerated', dirName: 'guides' }]);
});
