module.exports = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Guides',
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'guides' }],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
  ],
};
